// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module cursor.
import type { Id, Meta } from "solarsql";

// The id of a row of cursor_agents.
export type CursorAgentsId = Id<"cursor_agents">;

export type Generated = {
  "insert or ignore into cursor_agents (composer_id, name, status, unified_mode, model, worktree_path, branch_name, workspace_path, root, is_archived, is_subagent, created_at, updated_at)\n    select value ->> 'composer_id', value ->> 'name', value ->> 'status', value ->> 'unified_mode', value ->> 'model', value ->> 'worktree_path', value ->> 'branch_name', value ->> 'workspace_path', value ->> 'root', value ->> 'is_archived', value ->> 'is_subagent', value ->> 'created_at', value ->> 'updated_at'\n    from json_each(:rows)": {
    params: { rows: readonly { "composer_id": CursorAgentsId; "name": string | null; "status": string | null; "unified_mode": string | null; "model": string | null; "worktree_path": string | null; "branch_name": string | null; "workspace_path": string | null; "root": string | null; "is_archived": number | null; "is_subagent": number | null; "created_at": number | null; "updated_at": number | null }[] };
    row: {};
  };
  "select composer_id, name, status, unified_mode, model, worktree_path, branch_name, workspace_path, root, is_archived, is_subagent, created_at, updated_at\n    from cursor_agents order by cast(coalesce(updated_at, -1) as integer) desc, composer_id": {
    params: {};
    row: { composer_id: CursorAgentsId; name: string | null; status: string | null; unified_mode: string | null; model: string | null; worktree_path: string | null; branch_name: string | null; workspace_path: string | null; root: string | null; is_archived: number | null; is_subagent: number | null; created_at: number | null; updated_at: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into cursor_agents (composer_id, name, status, unified_mode, model, worktree_path, branch_name, workspace_path, root, is_archived, is_subagent, created_at, updated_at)\n    select value ->> 'composer_id', value ->> 'name', value ->> 'status', value ->> 'unified_mode', value ->> 'model', value ->> 'worktree_path', value ->> 'branch_name', value ->> 'workspace_path', value ->> 'root', value ->> 'is_archived', value ->> 'is_subagent', value ->> 'created_at', value ->> 'updated_at'\n    from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "select composer_id, name, status, unified_mode, model, worktree_path, branch_name, workspace_path, root, is_archived, is_subagent, created_at, updated_at\n    from cursor_agents order by cast(coalesce(updated_at, -1) as integer) desc, composer_id": { params: [], encode: [], json: [], reads: ["cursor_agents"] },
};
