// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module skills.
import type { Id, Meta } from "solarsql";

// The id of a row of plugins.
export type PluginsId = Id<"plugins">;
// The id of a row of skills.
export type SkillsId = Id<"skills">;

export type Generated = {
  "insert or ignore into skills (path, source, agent, name, description, root, plugin)\n    select value ->> 'path', value ->> 'source', value ->> 'agent', value ->> 'name', value ->> 'description', value ->> 'root', value ->> 'plugin'\n    from json_each(:rows)": {
    params: { rows: readonly { "path": SkillsId; "source": string; "agent": string; "name": string; "description": string | null; "root": string | null; "plugin": string | null }[] };
    row: {};
  };
  "insert or ignore into plugins (id, agent, name, marketplace, version, path, installed_at, updated_at)\n    select value ->> 'id', value ->> 'agent', value ->> 'name', value ->> 'marketplace', value ->> 'version', value ->> 'path', value ->> 'installed_at', value ->> 'updated_at'\n    from json_each(:rows)": {
    params: { rows: readonly { "id": PluginsId; "agent": string; "name": string; "marketplace": string | null; "version": string | null; "path": string; "installed_at": number | null; "updated_at": number | null }[] };
    row: {};
  };
  "select path, source, agent, name, description, root, plugin from skills order by agent, source, name": {
    params: {};
    row: { path: SkillsId; source: string; agent: string; name: string; description: string | null; root: string | null; plugin: string | null };
  };
  "select path, source, agent, name, description, root, plugin from skills\n    where source in ('claude-user', 'claude-plugin', 'codex-user', 'codex-admin', 'codex-system', 'codex-plugin')\n       or (source in ('claude-project', 'codex-project') and root = :root)\n    order by agent, name": {
    params: { root: string | null };
    row: { path: SkillsId; source: string; agent: string; name: string; description: string | null; root: string | null; plugin: string | null };
  };
  "select id, agent, name, marketplace, version, path, installed_at, updated_at from plugins order by agent, name": {
    params: {};
    row: { id: PluginsId; agent: string; name: string; marketplace: string | null; version: string | null; path: string; installed_at: number | null; updated_at: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into skills (path, source, agent, name, description, root, plugin)\n    select value ->> 'path', value ->> 'source', value ->> 'agent', value ->> 'name', value ->> 'description', value ->> 'root', value ->> 'plugin'\n    from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "insert or ignore into plugins (id, agent, name, marketplace, version, path, installed_at, updated_at)\n    select value ->> 'id', value ->> 'agent', value ->> 'name', value ->> 'marketplace', value ->> 'version', value ->> 'path', value ->> 'installed_at', value ->> 'updated_at'\n    from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "select path, source, agent, name, description, root, plugin from skills order by agent, source, name": { params: [], encode: [], json: [], reads: ["skills"] },
  "select path, source, agent, name, description, root, plugin from skills\n    where source in ('claude-user', 'claude-plugin', 'codex-user', 'codex-admin', 'codex-system', 'codex-plugin')\n       or (source in ('claude-project', 'codex-project') and root = :root)\n    order by agent, name": { params: ["root"], encode: [], json: [], reads: ["skills"] },
  "select id, agent, name, marketplace, version, path, installed_at, updated_at from plugins order by agent, name": { params: [], encode: [], json: [], reads: ["plugins"] },
};
