// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module search-path.
import type { Id, Meta } from "solarsql";

// The id of a row of path_entries.
export type PathEntriesId = Id<"path_entries">;

export type Generated = {
  "insert into path_entries (position, dir, \"exists\", duplicate_of)\n     select value ->> 'position', value ->> 'dir', value ->> 'exists', value ->> 'duplicate_of'\n     from json_each(:entries)": {
    params: { entries: readonly { "position": PathEntriesId; "dir": string; "exists": number; "duplicate_of": number | null }[] };
    row: {};
  };
  "insert into path_commands (name, dir, position, effective)\n     select value ->> 'name', value ->> 'dir', value ->> 'position', value ->> 'effective'\n     from json_each(:commands)": {
    params: { commands: readonly { "name": string; "dir": string; "position": number; "effective": 0 | 1 }[] };
    row: {};
  };
  "select position, dir, \"exists\", duplicate_of from path_entries order by position": {
    params: {};
    row: { position: PathEntriesId; dir: string; exists: number; duplicate_of: number | null };
  };
  "select name, dir, position, effective from path_commands where name = :q order by position": {
    params: { q: string };
    row: { name: string; dir: string; position: number; effective: 0 | 1 };
  };
  "select p.name, p.dir as effective_dir,\n    cast(group_concat(s.dir order by s.position) as text) as shadowed_dirs\n    from path_commands p join path_commands s on s.name = p.name\n    where p.effective = 1 and s.dir <> p.dir\n      and s.position = (\n        select min(candidate.position) from path_commands candidate\n        where candidate.name = s.name and candidate.dir = s.dir\n      )\n    group by p.name, p.dir\n    order by p.name": {
    params: {};
    row: { name: string; effective_dir: string; shadowed_dirs: string | null };
  };
};

export const generated: Meta<Generated> = {
  "insert into path_entries (position, dir, \"exists\", duplicate_of)\n     select value ->> 'position', value ->> 'dir', value ->> 'exists', value ->> 'duplicate_of'\n     from json_each(:entries)": { params: ["entries"], encode: ["entries"], json: [], reads: [] },
  "insert into path_commands (name, dir, position, effective)\n     select value ->> 'name', value ->> 'dir', value ->> 'position', value ->> 'effective'\n     from json_each(:commands)": { params: ["commands"], encode: ["commands"], json: [], reads: [] },
  "select position, dir, \"exists\", duplicate_of from path_entries order by position": { params: [], encode: [], json: [], reads: ["path_entries"] },
  "select name, dir, position, effective from path_commands where name = :q order by position": { params: ["q"], encode: [], json: [], reads: ["path_commands"] },
  "select p.name, p.dir as effective_dir,\n    cast(group_concat(s.dir order by s.position) as text) as shadowed_dirs\n    from path_commands p join path_commands s on s.name = p.name\n    where p.effective = 1 and s.dir <> p.dir\n      and s.position = (\n        select min(candidate.position) from path_commands candidate\n        where candidate.name = s.name and candidate.dir = s.dir\n      )\n    group by p.name, p.dir\n    order by p.name": { params: [], encode: [], json: [], reads: ["path_commands"] },
};
