// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module usage.
import type { Id, Meta } from "solarsql";

// The id of a row of claude_usage.
export type ClaudeUsageId = Id<"claude_usage">;
// The id of a row of codex_usage.
export type CodexUsageId = Id<"codex_usage">;

export type Generated = {
  "insert into claude_usage (id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source)\n    select value ->> 'id', value ->> 'limit_id', value ->> 'window_minutes', value ->> 'used_percent', value ->> 'resets_at', value ->> 'resets_text', value ->> 'recorded_at', value ->> 'source' from json_each(:rows)": {
    params: { rows: readonly { "id": ClaudeUsageId; "limit_id": string; "window_minutes": number | null; "used_percent": number; "resets_at": number | null; "resets_text": string | null; "recorded_at": number; "source": string }[] };
    row: {};
  };
  "insert into codex_usage (id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source)\n    select value ->> 'id', value ->> 'limit_id', value ->> 'window_minutes', value ->> 'used_percent', value ->> 'resets_at', value ->> 'resets_text', value ->> 'recorded_at', value ->> 'source' from json_each(:rows)": {
    params: { rows: readonly { "id": CodexUsageId; "limit_id": string; "window_minutes": number | null; "used_percent": number; "resets_at": number | null; "resets_text": string | null; "recorded_at": number; "source": string }[] };
    row: {};
  };
  "select id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source from claude_usage order by limit_id, window_minutes": {
    params: {};
    row: { id: ClaudeUsageId; limit_id: string; window_minutes: number | null; used_percent: number; resets_at: number | null; resets_text: string | null; recorded_at: number; source: string };
  };
  "select id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source from codex_usage order by limit_id, window_minutes": {
    params: {};
    row: { id: CodexUsageId; limit_id: string; window_minutes: number | null; used_percent: number; resets_at: number | null; resets_text: string | null; recorded_at: number; source: string };
  };
};

export const generated: Meta<Generated> = {
  "insert into claude_usage (id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source)\n    select value ->> 'id', value ->> 'limit_id', value ->> 'window_minutes', value ->> 'used_percent', value ->> 'resets_at', value ->> 'resets_text', value ->> 'recorded_at', value ->> 'source' from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "insert into codex_usage (id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source)\n    select value ->> 'id', value ->> 'limit_id', value ->> 'window_minutes', value ->> 'used_percent', value ->> 'resets_at', value ->> 'resets_text', value ->> 'recorded_at', value ->> 'source' from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "select id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source from claude_usage order by limit_id, window_minutes": { params: [], encode: [], json: [], reads: ["claude_usage"] },
  "select id, limit_id, window_minutes, used_percent, resets_at, resets_text, recorded_at, source from codex_usage order by limit_id, window_minutes": { params: [], encode: [], json: [], reads: ["codex_usage"] },
};
