// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module runtag.
import type { Id, Meta, SqlValue } from "solarsql";

// The id of a row of runtag_jobs.
export type RuntagJobsId = Id<"runtag_jobs">;

export type Generated = {
  "insert or replace into runtag_jobs (id, status, exit_code, orphan, repo_root, cwd, supervisor_pid)\n    select value ->> 'id', value ->> 'status', value ->> 'exit_code', value ->> 'orphan', value ->> 'repo_root', value ->> 'cwd', value ->> 'supervisor_pid'\n    from json_each(:rows)": {
    params: { rows: readonly { "id": RuntagJobsId; "status": "running" | "exited"; "exit_code": number | null; "orphan": 0 | 1; "repo_root": string | null; "cwd": string | null; "supervisor_pid": number | null }[] };
    row: {};
  };
  "\n    select id, status, exit_code, orphan, repo_root, cwd, supervisor_pid\n    from runtag_jobs\n    where exists (\n      select 1\n      from (select cast(case when rtrim(:root, '/') = '' then '/' else rtrim(:root, '/') end as text) as dir) bound\n      where (\n        repo_root is not null and repo_root <> '' and (\n          (case when rtrim(repo_root, '/') = '' then '/' else rtrim(repo_root, '/') end) = bound.dir\n          or (\n            bound.dir <> '/'\n            and substr(case when rtrim(repo_root, '/') = '' then '/' else rtrim(repo_root, '/') end, 1, length(bound.dir) + 1) = bound.dir || '/'\n          )\n          or (bound.dir = '/' and substr(repo_root, 1, 1) = '/')\n        )\n      ) or (\n        cwd is not null and cwd <> '' and (\n          (case when rtrim(cwd, '/') = '' then '/' else rtrim(cwd, '/') end) = bound.dir\n          or (\n            bound.dir <> '/'\n            and substr(case when rtrim(cwd, '/') = '' then '/' else rtrim(cwd, '/') end, 1, length(bound.dir) + 1) = bound.dir || '/'\n          )\n          or (bound.dir = '/' and substr(cwd, 1, 1) = '/')\n        )\n      )\n    )\n    order by id": {
    params: { root: SqlValue };
    row: { id: RuntagJobsId; status: "running" | "exited"; exit_code: number | null; orphan: 0 | 1; repo_root: string | null; cwd: string | null; supervisor_pid: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or replace into runtag_jobs (id, status, exit_code, orphan, repo_root, cwd, supervisor_pid)\n    select value ->> 'id', value ->> 'status', value ->> 'exit_code', value ->> 'orphan', value ->> 'repo_root', value ->> 'cwd', value ->> 'supervisor_pid'\n    from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "\n    select id, status, exit_code, orphan, repo_root, cwd, supervisor_pid\n    from runtag_jobs\n    where exists (\n      select 1\n      from (select cast(case when rtrim(:root, '/') = '' then '/' else rtrim(:root, '/') end as text) as dir) bound\n      where (\n        repo_root is not null and repo_root <> '' and (\n          (case when rtrim(repo_root, '/') = '' then '/' else rtrim(repo_root, '/') end) = bound.dir\n          or (\n            bound.dir <> '/'\n            and substr(case when rtrim(repo_root, '/') = '' then '/' else rtrim(repo_root, '/') end, 1, length(bound.dir) + 1) = bound.dir || '/'\n          )\n          or (bound.dir = '/' and substr(repo_root, 1, 1) = '/')\n        )\n      ) or (\n        cwd is not null and cwd <> '' and (\n          (case when rtrim(cwd, '/') = '' then '/' else rtrim(cwd, '/') end) = bound.dir\n          or (\n            bound.dir <> '/'\n            and substr(case when rtrim(cwd, '/') = '' then '/' else rtrim(cwd, '/') end, 1, length(bound.dir) + 1) = bound.dir || '/'\n          )\n          or (bound.dir = '/' and substr(cwd, 1, 1) = '/')\n        )\n      )\n    )\n    order by id": { params: ["root"], encode: [], json: [], reads: ["runtag_jobs"] },
};
